eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    healthcheck:
      enabled: true
    instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10
    registry-fetch-interval-seconds: 5
    # 此应用为注册中心，false：不向注册中心注册自己。
    register-with-eureka: false
    # 注册中心职责是维护服务实例，false：不检索服务。
    fetch-registry: false
  instance:
    hostname: localhost

server:
  port: 9001
spring:
  application:
    name: client